# Generated by Django 5.2.17 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming Languages'), ('Data & Analytics', 'Data & Analytics'), ('AI & Machine Learning', 'AI & Machine Learning'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Web Development', 'Web Development'), ('Cyber Security', 'Cyber Security'), ('Database', 'Database Management'), ('Soft Skills', 'Soft Skills & Leadership')], default='Programming', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('market_demand_weight', models.FloatField(default=1.0, help_text='Weight from 0.1 to 2.0 based on current market job postings')),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
