# Generated by Django 5.2.17 on 2026-09-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Python', 'Python Programming'), ('SQL', 'SQL & Database Queries'), ('HTML/CSS', 'HTML/CSS & Frontend'), ('JavaScript', 'JavaScript Fundamentals'), ('Data Structures', 'Data Structures & Algorithms'), ('AI/ML', 'AI & Machine Learning'), ('Power BI', 'Business Intelligence & Power BI'), ('Cloud Computing', 'Cloud Computing & AWS/GCP'), ('Communication', 'Communication & Professional Skills'), ('Problem Solving', 'Aptitude & Problem Solving')], default='Python', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.IntegerField(default=15)),
                ('total_questions', models.IntegerField(default=5)),
                ('passing_score', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=2)),
                ('explanation', models.TextField(blank=True, default='')),
                ('sub_skill', models.CharField(default='Core Concept', max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percentage', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('strong_skills', models.JSONField(default=list)),
                ('moderate_skills', models.JSONField(default=list)),
                ('weak_skills', models.JSONField(default=list)),
                ('answers_record', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
