# Generated by Django 5.2.17 on 2026-09-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='learners.studentprofile'),
        ),
    ]
