# Generated by Django 5.2.17 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('Information Technology', 'Information Technology & Software'), ('BFSI / FinTech', 'Banking, Financial Services & Insurance'), ('Healthcare & MedTech', 'Healthcare & Medical Technology'), ('Manufacturing & Auto', 'Manufacturing & Automotive'), ('E-Commerce & Retail', 'E-Commerce & Retail'), ('Telecom & Networking', 'Telecom & Networking'), ('Education & EdTech', 'Education & EdTech'), ('Government & Public Sector', 'Government & Public Sector')], default='Information Technology', max_length=100)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('district', models.CharField(default='Bengaluru', max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('company_size', models.CharField(default='50-250 Employees', max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
