# Generated by Django 5.2.17 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('education', models.CharField(default='B.Tech in Computer Science', max_length=150)),
                ('college_institute', models.CharField(default='Government Engineering College, Pune', max_length=200)),
                ('location', models.CharField(default='Pune, Maharashtra', max_length=100)),
                ('district', models.CharField(default='Pune', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('career_interests', models.CharField(default='Data Analyst, Python Developer, AI Engineer', max_length=255)),
                ('target_role', models.CharField(default='Junior Data Analyst', max_length=100)),
                ('experience_years', models.FloatField(default=0.0)),
                ('bio', models.TextField(blank=True, default='Passionate learner enthusiastic about software engineering, data analytics, and cloud technologies.')),
                ('certifications', models.TextField(blank=True, default='National Apprenticeship Certificate (NAC), Python for Data Science')),
                ('employment_status', models.CharField(choices=[('Seeking Opportunities', 'Seeking Opportunities'), ('Not Employed', 'Not Employed'), ('In Training', 'Currently in Training'), ('Employed / Placed', 'Employed / Placed'), ('Self-Employed / Freelancer', 'Self-Employed / Freelancer')], default='Seeking Opportunities', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_percentage', models.IntegerField(default=50, help_text='Current estimated proficiency from 0 to 100')),
                ('assessment_score', models.IntegerField(default=0, help_text='Most recent formal assessment score 0 to 100')),
                ('last_assessed_date', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-proficiency_percentage'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Certified', 'Certified'), ('Dropped', 'Dropped')], default='In Progress', max_length=30)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('pre_assessment_score', models.IntegerField(default=40, help_text='Benchmark score before training')),
                ('post_assessment_score', models.IntegerField(default=75, help_text='Measured score after training')),
                ('enrolled_date', models.DateField(auto_now_add=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
