# Generated by Django 5.2.17 on 2026-09-29 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('institutes', '0002_initial'),
        ('learners', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_proficiencies', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='learners.studentprofile'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_students', to='institutes.traininginstitute'),
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to='learners.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill')},
        ),
    ]
