# Generated by Django 5.2.17 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview Scheduled'), ('Selected', 'Selected / Hired'), ('Rejected', 'Not Selected')], default='Applied', max_length=30)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('match_score', models.FloatField(default=70.0, help_text='Calculated skill match percentage at application time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('salary_lpa', models.FloatField(default=6.0, help_text='Annual CTC in Lakhs Per Annum')),
                ('placement_date', models.DateField()),
                ('placement_type', models.CharField(choices=[('Government Skilling Drive', 'Government Skilling Drive Placement'), ('Campus Placement', 'Campus Placement via Institute'), ('Direct Industry Hire', 'Direct Industry Hire'), ('Apprenticeship Conversion', 'Apprenticeship Conversion')], default='Government Skilling Drive', max_length=60)),
                ('verified_by_institute', models.BooleanField(default=True)),
                ('verified_by_government', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-placement_date'],
            },
        ),
    ]
