# Generated by Django 5.2.17 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(default='National Skill Development Mission', max_length=150)),
                ('category', models.CharField(default='Data & Analytics', max_length=100)),
                ('duration_weeks', models.IntegerField(default=8)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('course_url', models.CharField(blank=True, default='https://swayam.gov.in', max_length=300)),
                ('price', models.IntegerField(default=0, help_text='Cost in INR (0 = Free/Govt Sponsored)')),
                ('certificate_provided', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_proficiency', models.IntegerField(default=75, help_text='Target proficiency level (0-100)% delivered by course')),
            ],
        ),
    ]
