# Generated by Django 5.2.17 on 2026-09-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('institutes', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='institutes.traininginstitute'),
        ),
        migrations.AddField(
            model_name='courseskill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='courseskill',
            unique_together={('course', 'skill')},
        ),
    ]
