# Generated by Django 5.2.17 on 2026-09-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department', models.CharField(default='Technology & Analytics', max_length=100)),
                ('location', models.CharField(default='Pune, Maharashtra', max_length=150)),
                ('district', models.CharField(default='Pune', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('salary_min', models.IntegerField(default=400000, help_text='Minimum Annual Salary in INR')),
                ('salary_max', models.IntegerField(default=800000, help_text='Maximum Annual Salary in INR')),
                ('experience_min', models.IntegerField(default=0, help_text='Minimum years of experience')),
                ('experience_max', models.IntegerField(default=2, help_text='Maximum years of experience')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Apprenticeship', 'Apprenticeship'), ('Contract', 'Contract')], default='Full-time', max_length=30)),
                ('vacancies', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_proficiency', models.IntegerField(default=70, help_text='Required proficiency from 0 to 100')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0, help_text='Relative weight for matching algorithms')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='skills.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
